# Generated by Django 5.1.3 on 2024-12-08 19:56

import django.utils.timezone
import travelog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이 사진의 이름을 입력해주세요.', max_length=255, verbose_name='Photo Name')),
                ('memo', models.TextField(blank=True, help_text='이 사진과 관련된 기억을 기록해 보세요', null=True, verbose_name='Photo Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='사진을 찍은 날짜는 어떨게 되나요?', verbose_name='Creation Timestamp')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude coordinate', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude coordinate', max_digits=9, null=True, verbose_name='Longitude')),
                ('photo_file', models.ImageField(blank=True, help_text='Actual photo file upload', null=True, upload_to=travelog.models.photo_upload_path, verbose_name='Photo File')),
            ],
            options={
                'verbose_name': 'Photo Metadata',
                'verbose_name_plural': 'Photos Metadata',
                'ordering': ['-created_at'],
            },
        ),
    ]
