# Generated by Django 5.1.3 on 2024-12-12 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('travel_main_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='사진을 찍은 날짜는 언제인가요?', verbose_name='Creation Timestamp'),
        ),
    ]
